// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnn4tl2Nm5wFZDPhl7raFWaNHroavk8y0',
    appId: '1:315109985206:web:2208067dcf651c7f708f17',
    messagingSenderId: '315109985206',
    projectId: 'ecoscrap-capstone',
    authDomain: 'ecoscrap-capstone.firebaseapp.com',
    storageBucket: 'ecoscrap-capstone.firebasestorage.app',
    measurementId: 'G-WCEZPFQMVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbdR0EJiT9uxQw0A24LFohzp9otl-UB9A',
    appId: '1:315109985206:android:d70dc2c752679592708f17',
    messagingSenderId: '315109985206',
    projectId: 'ecoscrap-capstone',
    storageBucket: 'ecoscrap-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkIUJ1jF0D06qt9trMpNhKTks0CJOYeLo',
    appId: '1:315109985206:ios:4f5a66f8ee66d3f8708f17',
    messagingSenderId: '315109985206',
    projectId: 'ecoscrap-capstone',
    storageBucket: 'ecoscrap-capstone.firebasestorage.app',
    iosBundleId: 'com.example.ecoscrapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkIUJ1jF0D06qt9trMpNhKTks0CJOYeLo',
    appId: '1:315109985206:ios:4f5a66f8ee66d3f8708f17',
    messagingSenderId: '315109985206',
    projectId: 'ecoscrap-capstone',
    storageBucket: 'ecoscrap-capstone.firebasestorage.app',
    iosBundleId: 'com.example.ecoscrapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnn4tl2Nm5wFZDPhl7raFWaNHroavk8y0',
    appId: '1:315109985206:web:72bac22bc048fc96708f17',
    messagingSenderId: '315109985206',
    projectId: 'ecoscrap-capstone',
    authDomain: 'ecoscrap-capstone.firebaseapp.com',
    storageBucket: 'ecoscrap-capstone.firebasestorage.app',
    measurementId: 'G-RSM7VSTKDW',
  );
}
